In [5]:
import pandas as pd
import numpy as np

# 1. Create and display a one-dimensional array-like object using Pandas module
data = pd.Series([1, 2, 3, 4, 5])
print("One-dimensional array-like object using Pandas:")
print(data)
print()

# 2. Convert a Pandas Series to Python list and its type
series = pd.Series([1, 2, 3, 4, 5])
list_from_series = series.tolist()
print("Pandas Series converted to Python list:", list_from_series)
print("Type of converted list:", type(list_from_series))
print()

# 3. Add, subtract, multiply, and divide two Pandas Series
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 9])
addition = series1 + series2
subtraction = series1 - series2
multiplication = series1 * series2
division = series1 / series2
print("Addition:")
print(addition)
print("Subtraction:")
print(subtraction)
print("Multiplication:")
print(multiplication)
print("Division:")
print(division)
print()

# 4. Compare the elements of two Pandas Series
series3 = pd.Series([2, 4, 6, 8, 10])
series4 = pd.Series([1, 3, 5, 7, 10])
comparison = series3 == series4
print("Comparison of elements of two Pandas Series:")
print(comparison)
print()

# 5. Convert a dictionary to a Pandas series
dictionary = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
converted_series = pd.Series(dictionary)
print("Converted series:")
print(converted_series)
print()

# 6. Convert a NumPy array to a Pandas series
numpy_array = np.array([10, 20, 30, 40, 50])
converted_series = pd.Series(numpy_array)
print("Converted Pandas series:")
print(converted_series)
print()

# 7. Change the data type of given a column or a Series
series = pd.Series(['100', '200', 'python', '300.12', '400'])
converted_series = pd.to_numeric(series, errors='coerce')
print("Change the data type to numeric:")
print(converted_series)
print()

# 8. Convert the first column of a DataFrame to a Series
data = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]}
df = pd.DataFrame(data)
series_from_df = df['col1']
print("1st column as a Series:")
print(series_from_df)
print(type(series_from_df))
print()

# 9. Convert a given Series to an array
series = pd.Series(['100', '200', 'python', '300.12', '400'])
array_from_series = series.values
print("Series to an array:")
print(array_from_series)
print(type(array_from_series))
print()

# 10. Create a DataFrame from a dictionary and display it
data = {'X': [78, 85, 96, 80, 86], 'Y': [84, 94, 89, 83, 86], 'Z': [86, 97, 96, 72, 83]}
df = pd.DataFrame(data)
print("DataFrame from a dictionary:")
print(df)
print()

# 11. Create and display a DataFrame from a specified dictionary data which has the index labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
print("DataFrame with index labels:")
print(df)
print()

# 12. Display a summary of the basic information about a specified DataFrame and its data
print("Summary of the basic information about this DataFrame and its data:")
print(df.info())
print()

# 13. Get the first 3 rows of a given DataFrame
print("First three rows of the data frame:")
print(df.head(3))
print()

# 14. Select the 'name' and 'score' columns from the DataFrame
print("Select specific columns:")
print(df[['name', 'score']])
print()

# 15. Select specified columns and rows from a given data frame
print("Select specific columns and rows:")
print(df.loc[['b', 'd', 'f', 'g'], ['score', 'qualify']])
print()

# 16. Select the rows where the number of attempts in the examination is greater than 2
print("Number of attempts in the examination is greater than 2:")
print(df[df['attempts'] > 2])
print()

# 17. Count the number of rows and columns of a DataFrame
print("Number of Rows:", len(df))
print("Number of Columns:", len(df.columns))
print()

# 18. Select the rows where the score is missing (NaN)
print("Rows where score is missing:")
print(df[df['score'].isnull()])
print()

# 19. Select the rows where the score is between 15 and 20 (inclusive)
print("Rows where score is between 15 and 20 (inclusive):")
print(df[(df['score'] >= 15) & (df['score'] <= 20)])
print()

One-dimensional array-like object using Pandas:
0    1
1    2
2    3
3    4
4    5
dtype: int64

Pandas Series converted to Python list: [1, 2, 3, 4, 5]
Type of converted list: <class 'list'>

Addition:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtraction:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiplication:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Division:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

Comparison of elements of two Pandas Series:
0    False
1    False
2    False
3    False
4     True
dtype: bool

Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64

Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

Change the data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>

Series to an array:
['100' '200' 'python' '300.12' '400']
<class 'numpy.ndarray'>

DataFrame from a dictionary:
    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

DataFrame with index labels:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Summary of the basic information about this DataFrame and its data:
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None

First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

Select specific columns:
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

Select specific columns and rows:
   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes

Number of attempts in the examination is greater than 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

Number of Rows: 10
Number of Columns: 4

Rows where score is missing:
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

Rows where score is between 15 and 20 (inclusive):
        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.2.1)
Requirement already satisfied: numpy<2,>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.